["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
ERC20MESH = [
    "./contracts/ERC20MESH.cairo",
]

LiquidityGauge = [
    "./contracts/gauges/LiquidityGauge.cairo",
]

Minter = [
    "./contracts/Minter.cairo",
]

VotingEscrow = [
    "./contracts/VotingEscrow.cairo",
]

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src"]