[project]
protostar-version = "0.9.1"
lib-path = "lib"

[contracts]
ERC20MESH = ["contracts/ERC20MESH.cairo"]
Minter = ["contracts/Minter.cairo"]
VotingEscrow = ["contracts/VotingEscrow.cairo"]
LiquidityGaugeV5 = ["contracts/LiquidityGaugeV5.cairo"]

