[package]
name = "jediswap_dao"
version = "0.1.0"
description = "A minimal template for developing with Cairo 1.0"
homepage = "https://github.com/auditless/cairo-template"

[scripts]
test = "protostar test"
# Add your own custom commands and run them with `scarb run <command>`

[dependencies]
starknet = ">=1.1.0"
# quaireaux_math = { git = "https://github.com/keep-starknet-strange/quaireaux.git" }

[[target.starknet-contract]]
