name: Tests

on: [push, pull_request]

env:
  ARTIFACT_RELEASE_ARCHIVE_LINK: https://api.github.com/repos/starkware-libs/cairo/actions/artifacts/689746858/zip
  ARTIFACT_RELEASE_ARCHIVE_NAME: cairo.zip
  RELEASE_ARCHIVE_NAME: x86_64-unknown-linux-musl.tar.gz
  SCARB_VERSION: v0.2.1
  PROTOSTAR_VERSION: 0.11.0

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install cairo compiler
        run: |
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o $ARTIFACT_RELEASE_ARCHIVE_NAME $ARTIFACT_RELEASE_ARCHIVE_LINK
          unzip $ARTIFACT_RELEASE_ARCHIVE_NAME
          tar -xvf $RELEASE_ARCHIVE_NAME

      - name: Check Cairo compiler version and add to path
        run: |
          $(pwd)/cairo/bin/cairo-compile --version
          echo "$(pwd)/cairo/bin" >> $GITHUB_PATH

      - name: Cache Scarb binary
        uses: actions/cache@v2
        with:
          path: ~/.scarb
          key: scarb-${{ env.SCARB_VERSION }}-${{ runner.os }}
          restore-keys: scarb-${{ env.SCARB_VERSION }}-

      - name: Scarb Setup
        run: |
          if [[ ! -f $HOME/.scarb/bin/scarb ]]; then
            wget https://github.com/software-mansion/scarb/releases/download/${{ env.SCARB_VERSION }}/scarb-${{ env.SCARB_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
            mkdir $HOME/.scarb
            tar -xvzf scarb-${{ env.SCARB_VERSION }}-x86_64-unknown-linux-gnu.tar.gz -C $HOME/.scarb --strip-components=1
          fi
          echo "$HOME/.scarb/bin" >> $GITHUB_PATH
      
      
      - name: Scarb Build
        run: scarb build

      - name: Cache Protostar installation
        uses: actions/cache@v2
        with:
          path: ~/.protostar
          key: protostar-${{ env.PROTOSTAR_VERSION }}-${{ runner.os }}
          restore-keys: protostar-${{ env.PROTOSTAR_VERSION }}-

      - name: Protostar Setup
        run: |
          if [[ ! -d $HOME/.protostar/dist/protostar ]]; then
            curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash -s -- -v $PROTOSTAR_VERSION
          fi
          echo "$HOME/.protostar/dist/protostar" >> $GITHUB_PATH
          
      - name: Test the code
        run: | 
          cairo-test --starknet .
